name: Upload S3
on: [push]
jobs:
  S3Publish:
    - uses: shallwefootball/upload-s3-action@v1.1.3
    with:
      # aws key id
      aws_key_id: AKIAZXTAJ4PNLORC2MMX
      # aws secret access key
      aws_secret_access_key: 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
      # aws bucket name
      aws_bucket: burkhardts.ninja
      # directory to upload
      source_dir: .
      # destination directory for upload
      #destination_dir: # optional, default is /
      run: echo "The job was automatically triggered by a ${{ github.event_name }} event."
